# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('caminho', models.ImageField(default='static/images/django.jpg', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=264, unique=True)),
                ('data', models.DateField()),
                ('texto', models.CharField(max_length=500)),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=200)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoticiasTabajara.Editor')),
                ('imagens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoticiasTabajara.Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoticiasTabajara.Pagina'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoticiasTabajara.Leitor'),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NoticiasTabajara.Pagina'),
        ),
    ]
