# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasTabajara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='pagina',
        ),
    ]
