# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasTabajara', '0003_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(default='static/images/django.jpg', upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(),
        ),
    ]
