# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasTabajara', '0005_auto_20171206_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='leitor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='noticia_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NoticiasTabajara.Noticia'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Leitor',
        ),
    ]
